# Custom Nginx configuration for OpenWISP under a single domain/IP catch-all

upstream dashboard {
    server dashboard:8000;
}

upstream api {
    server api:8001;
}

upstream websocket {
    server websocket:8002;
}

server {
    listen 80;
    server_name _;
    root /opt/openwisp/public/;

    # GZIP Configurations
    gzip on;
    gzip_comp_level 6;
    gzip_min_length 1000;
    gzip_types text/plain image/svg+xml application/json application/javascript text/xml text/css application/xml;

    add_header Strict-Transport-Security "max-age=31536000";
    add_header X-Content-Type-Options nosniff;

    # Route /ws/ to the websocket service
    location /ws/ {
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_redirect off;
        proxy_pass http://websocket;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    # Route static files (local volume)
    location /static/ {
        try_files /custom$uri $uri;
    }

    # Route media files (local volume)
    location /media/ {
        alias /opt/openwisp/public/media/;
    }

    # Route /api/ and /admin/api/ to the API service
    location /api/ {
        uwsgi_pass api;
        include uwsgi_params;
        uwsgi_param HTTP_X_FORWARDED_PROTO http;
        uwsgi_param REMOTE_ADDR $remote_addr;
    }

    # All other routes to the dashboard service
    location / {
        try_files /custom/maintenance.html $uri $uri/index.html @uwsgi_dashboard;
    }

    location @uwsgi_dashboard {
        uwsgi_pass dashboard;
        include uwsgi_params;
        uwsgi_param HTTP_X_FORWARDED_PROTO http;
        uwsgi_param REMOTE_ADDR $remote_addr;
    }
}
